### ISSUE TITLE
new region  shurima / version 3  support 

### ISSUE THREAD

**Issue by jotarun** [SwitchbladeBot/runeterra#11]
https://twitter.com/RiotGamesDevRel/status/1365415381859373057

**Comment by xTecna** [comment]
I've just sent a pull request with Shurima support, I hope it can solve this issue.

**Comment by chrysomallos** [comment]
Issue can be closed, support already merged by https://github.com/SwitchbladeBot/runeterra/pull/12, thx @xTecna
