### ISSUE TITLE
Encoding puts every card into the Demacia faction

### ISSUE THREAD

**Issue by etnmoussillac** [SwitchbladeBot/runeterra#3]
When encoding, all the card factions are set to 'DE' which makes the encoding code of non-Demacia decks wrong

**Comment by davipatury** [comment]
Could you show us an example?

**Comment by etnmoussillac** [comment]
Yes, if I use the first deck that you have in deckCodesTestData.txt, here is the output of the list before I encode the cards, then the cards after I decode them : http://prntscr.com/pofc1v
The decoding seem to be working fine for any type of deck, so my guess is that the encoding is at fault

**Comment by pedrofracassi** [comment]
How are tests even passing then? That's weird.

**Comment by davipatury** [comment]
Use `Card.from` or `Card.fromCardString` to create your deck.

PS.: The faction property should be a `Faction`, not a string, that's why it's "broken".

**Comment by etnmoussillac** [comment]
The problem was indeed that I was creating the `Faction` as a string on my own. It works perfectly fine with `Card.fromCardString`. Thank you very much for the quick answers!

**Comment by davipatury** [comment]
No problem!
