### ISSUE TITLE
Future proofing

### ISSUE THREAD

**Issue by miketromba** [SwitchbladeBot/runeterra#4]
I noticed this library has the factions hard-coded in. In terms of future-proofing, it might be best to find the faction shortcode based on a .slice() of the cardID instead of comparing the cardID to an array of faction shortcodes.

https://github.com/SwitchbladeBot/runeterra/blob/cca8b7452bf653da75b5719e76e4fdb943c57f25/src/Faction.js#L7-L10

https://github.com/SwitchbladeBot/runeterra/blob/cca8b7452bf653da75b5719e76e4fdb943c57f25/src/Faction.js#L17

**Comment by pedrofracassi** [comment]
We're following the way it works in the [original library by Riot](https://github.com/RiotGames/LoRDeckCodes/blob/77470773c4b11e308a5311ae379fac54e644189c/LoRDeckCodes/LoRDeckEncoder.cs#L19-L32).
